version: "3.7"
services:
  metad0:
    image: vesoft/nebula-metad:v3.3.0
    environment:
      USER: root
      TZ: "Asia/Shanghai"
    command:
      - --meta_server_addrs=metad0:9559
      - --local_ip=metad0
      - --ws_ip=metad0
      - --port=9559
      - --ws_http_port=19559
      - --data_path=/data/meta
      - --log_dir=/logs
      - --v=0
      - --minloglevel=0
    ports:
      - "9559:9559"
    volumes:
      - ./nebula/meta/data:/data/meta
      - ./nebula/meta/logs:/logs
    cap_add:
      - SYS_PTRACE

  storaged0:
    image: vesoft/nebula-storaged:v3.3.0
    environment:
      USER: root
      TZ:   "Asia/Shanghai"
    command:
      - --meta_server_addrs=metad0:9559
      - --local_ip=storaged0
      - --ws_ip=storaged0
      - --port=9779
      - --ws_http_port=19779
      - --data_path=/data/storage
      - --log_dir=/logs
      - --v=0
      - --minloglevel=0
    depends_on:
      - metad0
    ports:
      - "9779:9779"
      - "19779:19779"
    volumes:
      - ./nebula/storage/data:/data/storage
      - ./nebula/storage/logs:/logs
    cap_add:
      - SYS_PTRACE

  graphd:
    image: vesoft/nebula-graphd:v3.3.0
    environment:
      USER: root
      TZ: "Asia/Shanghai"
    command:
      - --meta_server_addrs=metad0:9559
      - --port=9669
      - --local_ip=graphd
      - --ws_ip=graphd
      - --ws_http_port=19669
      - --log_dir=/logs
      - --v=0
      - --minloglevel=0
    depends_on:
      - storaged0
    ports:
      - "9669:9669"
    volumes:
      - ./nebula/graphd/logs:/logs
    cap_add:
      - SYS_PTRACE